USE [master]
GO

/****** Object:  Database [MusicMausoleumDB]    Script Date: 10/10/2021 06:24:42 PM ******/
CREATE DATABASE [MusicMausoleumDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MusicMausoleumDB', FILENAME = N'C:\Users\Alesi\MusicMausoleumDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MusicMausoleumDB_log', FILENAME = N'C:\Users\Alesi\MusicMausoleumDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MusicMausoleumDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MusicMausoleumDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MusicMausoleumDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MusicMausoleumDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MusicMausoleumDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MusicMausoleumDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MusicMausoleumDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [MusicMausoleumDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MusicMausoleumDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MusicMausoleumDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MusicMausoleumDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MusicMausoleumDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MusicMausoleumDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MusicMausoleumDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MusicMausoleumDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MusicMausoleumDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MusicMausoleumDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MusicMausoleumDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MusicMausoleumDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MusicMausoleumDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MusicMausoleumDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MusicMausoleumDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MusicMausoleumDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MusicMausoleumDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MusicMausoleumDB] SET  MULTI_USER 
GO

ALTER DATABASE [MusicMausoleumDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MusicMausoleumDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MusicMausoleumDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MusicMausoleumDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MusicMausoleumDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MusicMausoleumDB] SET QUERY_STORE = OFF
GO

USE [MusicMausoleumDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [MusicMausoleumDB] SET  READ_WRITE 
GO

